name: apstoolsdoc
channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge
dependencies:
  - python >=3.6.0
  - aps-dm-api
  - bluesky >=1.6.2
  - databroker >=1.0.6
  - databroker-pack
  - h5py
  - hklpy
  - openpyxl
  - ophyd >=1.5.1
  - pandas
  - pip
  - pyEpics >=3.4.2
  - pyqt =5
  - pyRestTable
  - qt =5
  - spec2nexus >=2021.1.7
  - sphinx
  - pip:
    - bluesky_live
    - ipython-genutils==0.2.0
    - prompt-toolkit==1.0.15
    - sphinx-rtd-theme
    - super-state-machine
    - versioneer
