name: apstoolsdoc
channels:
- nsls2forge
- defaults
dependencies:
- python=3.6
- qt=5
- pyqt=5
- sphinx
- sphinx_rtd_theme
- bluesky
- ophyd
- prettytable
- pip:
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.15
  - sphinx-rtd-theme
  - super-state-machine
  - versioneer
