{% set version = "0.0.3" %}

package:
    name: aps_bluesky_tools
    version: {{ version }}

source:
    git_rev: {{ version }}
    git_url:  https://github.com/BCDA-APS/APS_BlueSky_tools.git

requirements:

  build:
    - python
    - setuptools

  run:
    - python

test:

    imports:
        - APS_BlueSky_tools

    commands:
        - python run_test.py

about:
    home: http://APS_BlueSky_tools.readthedocs.io
    license_file: APS_BlueSky_tools/LICENSE
    license: Creative Commons Attribution 4.0 International Public License
    summary: 'Format a nice table in reST (reStructuredText ) from Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
# https://conda.io/docs/build_tutorials/pkgs.html
