{% set name = "apstools" %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

about:
  summary: Various Python tools for use with Bluesky at the APS
  home: https://github.com/prjemian/apstools
  license: (c) 2017-2019, UChicago Argonne, LLC (see file for details)
  license_file: ../LICENSE.txt
  readme: ../README.md
  doc_url: https://apstools.readthedocs.org

source:
  path: ../

build:
  number: 1
  script: python setup.py install
  noarch: python
  entry_points:
    - apstools_plan_catalog = apstools.examples:main
    - bluesky_snapshot = apstools.snapshot:snapshot_cli
    - bluesky_snapshot_viewer = apstools.snapshot:snapshot_gui
  # script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python  {{ python }}
    - ophyd
    - databroker
    - bluesky
    - pyRestTable
  run:
    - python
    - ophyd
    - databroker
    - bluesky
    - pyRestTable

test:
  imports:
    - apstools
    - apstools.synApps_ophyd
  commands:
    - python -c "import apstools;"
    # - apstools_plan_catalog --help
    - bluesky_snapshot --help
    # - bluesky_snapshot_viewer --help

extra:
  recipe-maintainers:
    - prjemian
